version: '3.7'
services:
  web:
    build: .
    container_name: kottage
    ports:
      - "8080:8080"
    env_file:
      - .env
      - .db-env
    depends_on:
      - db
      - redis
  db:
    image: mysql:latest
    container_name: kottage_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .db-env
  redis:
    image: redis:latest
    container_name: kottage_redis
    restart: always
