version: '3.7'
services:
  web:
    build: .
    container_name: kottage
    ports:
      - "8080:8080"
    env_file:
      - .env
      - .db-env
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - .db-env
