services:
  web:
    build: .
    container_name: kottage
    ports:
      - "8080:8080"
    env_file:
      - .env
      - .db-env
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/api/v1/health"]
      interval: "5m"
      timeout: "10s"
      retries: 3
  db:
    platform: linux/amd64
    image: mysql:8.4
    container_name: kottage_db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .db-env
  redis:
    image: redis:latest
    container_name: kottage_redis
    restart: always
