version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - run: |
          mv .ci.env .env
          mv .ci.db-env .db-env
      - setup_remote_docker
      - run: sh docker-build.sh
      - run: ./gradlew clean test
      - store_artifacts:
          path: build/reports
      - store_artifacts:
          path: karate/build/reports
