version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - run: |
          mv .ci.env .env
          mv .ci.db-env .db-env
      - setup_remote_docker:
          version: 20.10.2
      - run:
          command: sh scripts/run-on-docker.sh
          background: true
      - run: ./gradlew test -x karate:test
      - run: sh scripts/run-e2e-test-on-docker.sh
      - run: docker-compose stop
      - store_artifacts:
          path: build/reports
      - store_artifacts:
          path: karate/build/reports
