name: Publish Docker image

on:
  push:
    branches:
      - 'master'
      - 'feature/cd' # to test this workflow

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: miyado/kottage
          tags: |
            type=schedule,pattern={{date 'YYYYMMDDHHmm'}},prefix=v1-

      - name: git setting
        run: |
          git config --local user.email "hmiyado@gmail.com"
          git config --local user.name "hmiyado"

      - name: Version up
        run: sh scripts/update-version.sh ${{ steps.meta.outputs.tags[0].value }}

      - name: Build distribution app
        run: ./gradlew clean installDist

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push updated version
        run: git push
