name: Update version

on:
  push:
    branches:
      - 'release/v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: miyado/kottage
          tags: |
            type=semver,pattern={{version}}

      - name: git setting
        run: |
          git config --local user.email "hmiyado@gmail.com"
          git config --local user.name "hmiyado"

      - name: Version up
        run: sh scripts/update-version.sh ${{ steps.meta.outputs.tags[0].value }}

      - name: Push updated version
        run: git push
